#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_Employee")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Employee_Master(tbl_Employee_Master instance);
    partial void Updatetbl_Employee_Master(tbl_Employee_Master instance);
    partial void Deletetbl_Employee_Master(tbl_Employee_Master instance);
    partial void Inserttbl_Educational_Detail(tbl_Educational_Detail instance);
    partial void Updatetbl_Educational_Detail(tbl_Educational_Detail instance);
    partial void Deletetbl_Educational_Detail(tbl_Educational_Detail instance);
    partial void Inserttbl_Error_Log(tbl_Error_Log instance);
    partial void Updatetbl_Error_Log(tbl_Error_Log instance);
    partial void Deletetbl_Error_Log(tbl_Error_Log instance);
    partial void Inserttbl_User_Master(tbl_User_Master instance);
    partial void Updatetbl_User_Master(tbl_User_Master instance);
    partial void Deletetbl_User_Master(tbl_User_Master instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_EmployeeConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Employee_Master> tbl_Employee_Masters
		{
			get
			{
				return this.GetTable<tbl_Employee_Master>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Educational_Detail> tbl_Educational_Details
		{
			get
			{
				return this.GetTable<tbl_Educational_Detail>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Error_Log> tbl_Error_Logs
		{
			get
			{
				return this.GetTable<tbl_Error_Log>();
			}
		}
		
		public System.Data.Linq.Table<tbl_User_Master> tbl_User_Masters
		{
			get
			{
				return this.GetTable<tbl_User_Master>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Proc_tbl_Employee_Master_Insert_Data")]
		public int Proc_tbl_Employee_Master_Insert_Data([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Employee_Name", DbType="VarChar(100)")] string employee_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contact_No", DbType="VarChar(20)")] string contact_No, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address1", DbType="VarChar(100)")] string address1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address2", DbType="VarChar(100)")] string address2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="VarChar(100)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="State", DbType="VarChar(100)")] string state, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Country", DbType="VarChar(100)")] string country, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Zipcode", DbType="VarChar(10)")] string zipcode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), employee_Name, contact_No, email, address1, address2, city, state, country, zipcode);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Proc_tbl_Employee_Master_Select_All")]
		public ISingleResult<Proc_tbl_Employee_Master_Select_AllResult> Proc_tbl_Employee_Master_Select_All()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Proc_tbl_Employee_Master_Select_AllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Proc_tbl_Employee_Master_Select_By_Id")]
		public ISingleResult<Proc_tbl_Employee_Master_Select_By_IdResult> Proc_tbl_Employee_Master_Select_By_Id([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Employee_Id", DbType="Int")] System.Nullable<int> employee_Id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), employee_Id);
			return ((ISingleResult<Proc_tbl_Employee_Master_Select_By_IdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Proc_tbl_Employee_Master_Update_Data")]
		public int Proc_tbl_Employee_Master_Update_Data([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Employee_Id", DbType="Int")] System.Nullable<int> employee_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Employee_Name", DbType="VarChar(100)")] string employee_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contact_No", DbType="VarChar(20)")] string contact_No, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address1", DbType="VarChar(100)")] string address1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address2", DbType="VarChar(100)")] string address2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="VarChar(100)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="State", DbType="VarChar(100)")] string state, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Country", DbType="VarChar(100)")] string country, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Zipcode", DbType="VarChar(10)")] string zipcode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), employee_Id, employee_Name, contact_No, email, address1, address2, city, state, country, zipcode);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Proc_tbl_Employee_Master_Update_Status")]
		public int Proc_tbl_Employee_Master_Update_Status([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Employee_Id", DbType="Int")] System.Nullable<int> employee_Id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), employee_Id, status);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Employee_Master")]
	public partial class tbl_Employee_Master : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Employee_Id;
		
		private string _Employee_Name;
		
		private string _Contact_No;
		
		private string _Email;
		
		private string _Address_Line1;
		
		private string _Address_Line2;
		
		private string _City;
		
		private string _State;
		
		private string _Country;
		
		private string _Zip_Code;
		
		private bool _Active_Status;
		
		private EntitySet<tbl_Educational_Detail> _tbl_Educational_Details;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmployee_IdChanging(int value);
    partial void OnEmployee_IdChanged();
    partial void OnEmployee_NameChanging(string value);
    partial void OnEmployee_NameChanged();
    partial void OnContact_NoChanging(string value);
    partial void OnContact_NoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnAddress_Line1Changing(string value);
    partial void OnAddress_Line1Changed();
    partial void OnAddress_Line2Changing(string value);
    partial void OnAddress_Line2Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnZip_CodeChanging(string value);
    partial void OnZip_CodeChanged();
    partial void OnActive_StatusChanging(bool value);
    partial void OnActive_StatusChanged();
    #endregion
		
		public tbl_Employee_Master()
		{
			this._tbl_Educational_Details = new EntitySet<tbl_Educational_Detail>(new Action<tbl_Educational_Detail>(this.attach_tbl_Educational_Details), new Action<tbl_Educational_Detail>(this.detach_tbl_Educational_Details));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Employee_Id
		{
			get
			{
				return this._Employee_Id;
			}
			set
			{
				if ((this._Employee_Id != value))
				{
					this.OnEmployee_IdChanging(value);
					this.SendPropertyChanging();
					this._Employee_Id = value;
					this.SendPropertyChanged("Employee_Id");
					this.OnEmployee_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_Name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Employee_Name
		{
			get
			{
				return this._Employee_Name;
			}
			set
			{
				if ((this._Employee_Name != value))
				{
					this.OnEmployee_NameChanging(value);
					this.SendPropertyChanging();
					this._Employee_Name = value;
					this.SendPropertyChanged("Employee_Name");
					this.OnEmployee_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact_No", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Contact_No
		{
			get
			{
				return this._Contact_No;
			}
			set
			{
				if ((this._Contact_No != value))
				{
					this.OnContact_NoChanging(value);
					this.SendPropertyChanging();
					this._Contact_No = value;
					this.SendPropertyChanged("Contact_No");
					this.OnContact_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_Line1", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Address_Line1
		{
			get
			{
				return this._Address_Line1;
			}
			set
			{
				if ((this._Address_Line1 != value))
				{
					this.OnAddress_Line1Changing(value);
					this.SendPropertyChanging();
					this._Address_Line1 = value;
					this.SendPropertyChanged("Address_Line1");
					this.OnAddress_Line1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_Line2", DbType="VarChar(100)")]
		public string Address_Line2
		{
			get
			{
				return this._Address_Line2;
			}
			set
			{
				if ((this._Address_Line2 != value))
				{
					this.OnAddress_Line2Changing(value);
					this.SendPropertyChanging();
					this._Address_Line2 = value;
					this.SendPropertyChanged("Address_Line2");
					this.OnAddress_Line2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Zip_Code
		{
			get
			{
				return this._Zip_Code;
			}
			set
			{
				if ((this._Zip_Code != value))
				{
					this.OnZip_CodeChanging(value);
					this.SendPropertyChanging();
					this._Zip_Code = value;
					this.SendPropertyChanged("Zip_Code");
					this.OnZip_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active_Status", DbType="Bit NOT NULL")]
		public bool Active_Status
		{
			get
			{
				return this._Active_Status;
			}
			set
			{
				if ((this._Active_Status != value))
				{
					this.OnActive_StatusChanging(value);
					this.SendPropertyChanging();
					this._Active_Status = value;
					this.SendPropertyChanged("Active_Status");
					this.OnActive_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Employee_Master_tbl_Educational_Detail", Storage="_tbl_Educational_Details", ThisKey="Employee_Id", OtherKey="Employee_Id")]
		public EntitySet<tbl_Educational_Detail> tbl_Educational_Details
		{
			get
			{
				return this._tbl_Educational_Details;
			}
			set
			{
				this._tbl_Educational_Details.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Educational_Details(tbl_Educational_Detail entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Employee_Master = this;
		}
		
		private void detach_tbl_Educational_Details(tbl_Educational_Detail entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Employee_Master = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Educational_Details")]
	public partial class tbl_Educational_Detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Educational_Details_Id;
		
		private int _Employee_Id;
		
		private string _Education;
		
		private string _University;
		
		private string _Grade_Obtained;
		
		private string _Passing_Year;
		
		private bool _Active_Status;
		
		private EntityRef<tbl_Employee_Master> _tbl_Employee_Master;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEducational_Details_IdChanging(int value);
    partial void OnEducational_Details_IdChanged();
    partial void OnEmployee_IdChanging(int value);
    partial void OnEmployee_IdChanged();
    partial void OnEducationChanging(string value);
    partial void OnEducationChanged();
    partial void OnUniversityChanging(string value);
    partial void OnUniversityChanged();
    partial void OnGrade_ObtainedChanging(string value);
    partial void OnGrade_ObtainedChanged();
    partial void OnPassing_YearChanging(string value);
    partial void OnPassing_YearChanged();
    partial void OnActive_StatusChanging(bool value);
    partial void OnActive_StatusChanged();
    #endregion
		
		public tbl_Educational_Detail()
		{
			this._tbl_Employee_Master = default(EntityRef<tbl_Employee_Master>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Educational_Details_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Educational_Details_Id
		{
			get
			{
				return this._Educational_Details_Id;
			}
			set
			{
				if ((this._Educational_Details_Id != value))
				{
					this.OnEducational_Details_IdChanging(value);
					this.SendPropertyChanging();
					this._Educational_Details_Id = value;
					this.SendPropertyChanged("Educational_Details_Id");
					this.OnEducational_Details_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_Id", DbType="Int NOT NULL")]
		public int Employee_Id
		{
			get
			{
				return this._Employee_Id;
			}
			set
			{
				if ((this._Employee_Id != value))
				{
					if (this._tbl_Employee_Master.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmployee_IdChanging(value);
					this.SendPropertyChanging();
					this._Employee_Id = value;
					this.SendPropertyChanged("Employee_Id");
					this.OnEmployee_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Education", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Education
		{
			get
			{
				return this._Education;
			}
			set
			{
				if ((this._Education != value))
				{
					this.OnEducationChanging(value);
					this.SendPropertyChanging();
					this._Education = value;
					this.SendPropertyChanged("Education");
					this.OnEducationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_University", DbType="VarChar(1000)")]
		public string University
		{
			get
			{
				return this._University;
			}
			set
			{
				if ((this._University != value))
				{
					this.OnUniversityChanging(value);
					this.SendPropertyChanging();
					this._University = value;
					this.SendPropertyChanged("University");
					this.OnUniversityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade_Obtained", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Grade_Obtained
		{
			get
			{
				return this._Grade_Obtained;
			}
			set
			{
				if ((this._Grade_Obtained != value))
				{
					this.OnGrade_ObtainedChanging(value);
					this.SendPropertyChanging();
					this._Grade_Obtained = value;
					this.SendPropertyChanged("Grade_Obtained");
					this.OnGrade_ObtainedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passing_Year", DbType="VarChar(10)")]
		public string Passing_Year
		{
			get
			{
				return this._Passing_Year;
			}
			set
			{
				if ((this._Passing_Year != value))
				{
					this.OnPassing_YearChanging(value);
					this.SendPropertyChanging();
					this._Passing_Year = value;
					this.SendPropertyChanged("Passing_Year");
					this.OnPassing_YearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active_Status", DbType="Bit NOT NULL")]
		public bool Active_Status
		{
			get
			{
				return this._Active_Status;
			}
			set
			{
				if ((this._Active_Status != value))
				{
					this.OnActive_StatusChanging(value);
					this.SendPropertyChanging();
					this._Active_Status = value;
					this.SendPropertyChanged("Active_Status");
					this.OnActive_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Employee_Master_tbl_Educational_Detail", Storage="_tbl_Employee_Master", ThisKey="Employee_Id", OtherKey="Employee_Id", IsForeignKey=true)]
		public tbl_Employee_Master tbl_Employee_Master
		{
			get
			{
				return this._tbl_Employee_Master.Entity;
			}
			set
			{
				tbl_Employee_Master previousValue = this._tbl_Employee_Master.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Employee_Master.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Employee_Master.Entity = null;
						previousValue.tbl_Educational_Details.Remove(this);
					}
					this._tbl_Employee_Master.Entity = value;
					if ((value != null))
					{
						value.tbl_Educational_Details.Add(this);
						this._Employee_Id = value.Employee_Id;
					}
					else
					{
						this._Employee_Id = default(int);
					}
					this.SendPropertyChanged("tbl_Employee_Master");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Error_Log")]
	public partial class tbl_Error_Log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Error_Id;
		
		private string _Page_Name;
		
		private string _Method_Name;
		
		private string _Error_Message;
		
		private string _Stack_Trace;
		
		private System.Nullable<System.DateTime> _Created_Datetime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnError_IdChanging(int value);
    partial void OnError_IdChanged();
    partial void OnPage_NameChanging(string value);
    partial void OnPage_NameChanged();
    partial void OnMethod_NameChanging(string value);
    partial void OnMethod_NameChanged();
    partial void OnError_MessageChanging(string value);
    partial void OnError_MessageChanged();
    partial void OnStack_TraceChanging(string value);
    partial void OnStack_TraceChanged();
    partial void OnCreated_DatetimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCreated_DatetimeChanged();
    #endregion
		
		public tbl_Error_Log()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Error_Id
		{
			get
			{
				return this._Error_Id;
			}
			set
			{
				if ((this._Error_Id != value))
				{
					this.OnError_IdChanging(value);
					this.SendPropertyChanging();
					this._Error_Id = value;
					this.SendPropertyChanged("Error_Id");
					this.OnError_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Page_Name", DbType="NVarChar(500)")]
		public string Page_Name
		{
			get
			{
				return this._Page_Name;
			}
			set
			{
				if ((this._Page_Name != value))
				{
					this.OnPage_NameChanging(value);
					this.SendPropertyChanging();
					this._Page_Name = value;
					this.SendPropertyChanged("Page_Name");
					this.OnPage_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Method_Name", DbType="NVarChar(500)")]
		public string Method_Name
		{
			get
			{
				return this._Method_Name;
			}
			set
			{
				if ((this._Method_Name != value))
				{
					this.OnMethod_NameChanging(value);
					this.SendPropertyChanging();
					this._Method_Name = value;
					this.SendPropertyChanged("Method_Name");
					this.OnMethod_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error_Message", DbType="NVarChar(MAX)")]
		public string Error_Message
		{
			get
			{
				return this._Error_Message;
			}
			set
			{
				if ((this._Error_Message != value))
				{
					this.OnError_MessageChanging(value);
					this.SendPropertyChanging();
					this._Error_Message = value;
					this.SendPropertyChanged("Error_Message");
					this.OnError_MessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stack_Trace", DbType="NVarChar(MAX)")]
		public string Stack_Trace
		{
			get
			{
				return this._Stack_Trace;
			}
			set
			{
				if ((this._Stack_Trace != value))
				{
					this.OnStack_TraceChanging(value);
					this.SendPropertyChanging();
					this._Stack_Trace = value;
					this.SendPropertyChanged("Stack_Trace");
					this.OnStack_TraceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_Datetime", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created_Datetime
		{
			get
			{
				return this._Created_Datetime;
			}
			set
			{
				if ((this._Created_Datetime != value))
				{
					this.OnCreated_DatetimeChanging(value);
					this.SendPropertyChanging();
					this._Created_Datetime = value;
					this.SendPropertyChanged("Created_Datetime");
					this.OnCreated_DatetimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_User_Master")]
	public partial class tbl_User_Master : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _User_Id;
		
		private string _Username;
		
		private string _Password;
		
		private string _Full_Name;
		
		private System.Nullable<System.DateTime> _Last_Login_Datetime;
		
		private bool _Active_Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IdChanging(int value);
    partial void OnUser_IdChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnFull_NameChanging(string value);
    partial void OnFull_NameChanged();
    partial void OnLast_Login_DatetimeChanging(System.Nullable<System.DateTime> value);
    partial void OnLast_Login_DatetimeChanged();
    partial void OnActive_StatusChanging(bool value);
    partial void OnActive_StatusChanged();
    #endregion
		
		public tbl_User_Master()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Full_Name", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Full_Name
		{
			get
			{
				return this._Full_Name;
			}
			set
			{
				if ((this._Full_Name != value))
				{
					this.OnFull_NameChanging(value);
					this.SendPropertyChanging();
					this._Full_Name = value;
					this.SendPropertyChanged("Full_Name");
					this.OnFull_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Login_Datetime", DbType="DateTime")]
		public System.Nullable<System.DateTime> Last_Login_Datetime
		{
			get
			{
				return this._Last_Login_Datetime;
			}
			set
			{
				if ((this._Last_Login_Datetime != value))
				{
					this.OnLast_Login_DatetimeChanging(value);
					this.SendPropertyChanging();
					this._Last_Login_Datetime = value;
					this.SendPropertyChanged("Last_Login_Datetime");
					this.OnLast_Login_DatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active_Status", DbType="Bit NOT NULL")]
		public bool Active_Status
		{
			get
			{
				return this._Active_Status;
			}
			set
			{
				if ((this._Active_Status != value))
				{
					this.OnActive_StatusChanging(value);
					this.SendPropertyChanging();
					this._Active_Status = value;
					this.SendPropertyChanged("Active_Status");
					this.OnActive_StatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class Proc_tbl_Employee_Master_Select_AllResult
	{
		
		private int _Employee_Id;
		
		private string _Employee_Name;
		
		private string _Contact_No;
		
		private string _Email;
		
		private string _Address_Line1;
		
		private string _Address_Line2;
		
		private string _City;
		
		private string _State;
		
		private string _Country;
		
		private string _Zip_Code;
		
		private bool _Active_Status;
		
		public Proc_tbl_Employee_Master_Select_AllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_Id", DbType="Int NOT NULL")]
		public int Employee_Id
		{
			get
			{
				return this._Employee_Id;
			}
			set
			{
				if ((this._Employee_Id != value))
				{
					this._Employee_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_Name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Employee_Name
		{
			get
			{
				return this._Employee_Name;
			}
			set
			{
				if ((this._Employee_Name != value))
				{
					this._Employee_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact_No", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Contact_No
		{
			get
			{
				return this._Contact_No;
			}
			set
			{
				if ((this._Contact_No != value))
				{
					this._Contact_No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_Line1", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Address_Line1
		{
			get
			{
				return this._Address_Line1;
			}
			set
			{
				if ((this._Address_Line1 != value))
				{
					this._Address_Line1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_Line2", DbType="VarChar(100)")]
		public string Address_Line2
		{
			get
			{
				return this._Address_Line2;
			}
			set
			{
				if ((this._Address_Line2 != value))
				{
					this._Address_Line2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this._Country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Zip_Code
		{
			get
			{
				return this._Zip_Code;
			}
			set
			{
				if ((this._Zip_Code != value))
				{
					this._Zip_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active_Status", DbType="Bit NOT NULL")]
		public bool Active_Status
		{
			get
			{
				return this._Active_Status;
			}
			set
			{
				if ((this._Active_Status != value))
				{
					this._Active_Status = value;
				}
			}
		}
	}
	
	public partial class Proc_tbl_Employee_Master_Select_By_IdResult
	{
		
		private int _Employee_Id;
		
		private string _Employee_Name;
		
		private string _Contact_No;
		
		private string _Email;
		
		private string _Address_Line1;
		
		private string _Address_Line2;
		
		private string _City;
		
		private string _State;
		
		private string _Country;
		
		private string _Zip_Code;
		
		private bool _Active_Status;
		
		public Proc_tbl_Employee_Master_Select_By_IdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_Id", DbType="Int NOT NULL")]
		public int Employee_Id
		{
			get
			{
				return this._Employee_Id;
			}
			set
			{
				if ((this._Employee_Id != value))
				{
					this._Employee_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_Name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Employee_Name
		{
			get
			{
				return this._Employee_Name;
			}
			set
			{
				if ((this._Employee_Name != value))
				{
					this._Employee_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact_No", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Contact_No
		{
			get
			{
				return this._Contact_No;
			}
			set
			{
				if ((this._Contact_No != value))
				{
					this._Contact_No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_Line1", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Address_Line1
		{
			get
			{
				return this._Address_Line1;
			}
			set
			{
				if ((this._Address_Line1 != value))
				{
					this._Address_Line1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_Line2", DbType="VarChar(100)")]
		public string Address_Line2
		{
			get
			{
				return this._Address_Line2;
			}
			set
			{
				if ((this._Address_Line2 != value))
				{
					this._Address_Line2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this._Country = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip_Code", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Zip_Code
		{
			get
			{
				return this._Zip_Code;
			}
			set
			{
				if ((this._Zip_Code != value))
				{
					this._Zip_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active_Status", DbType="Bit NOT NULL")]
		public bool Active_Status
		{
			get
			{
				return this._Active_Status;
			}
			set
			{
				if ((this._Active_Status != value))
				{
					this._Active_Status = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
